### ISSUE TITLE
Create and select folders

### ISSUE THREAD

**Issue by jdtsmith** [mstratman/cocoadialog#35]
It would be useful to be able to create folders, and then select them in a single operation.  With version 2.1.1, you can select existing folders with `fileselect --select-only-directories`, or you can allow the user to create new folders with `filesave`, but you can't both create a new folder and then select it to return.  This would be useful for example for custom iPhoto export scripts, creating and returning a new folder to target the export.

**Comment by markcarver** [comment]
This is a relatively simple option to add. Should probably be `--create-directories`.
