### ISSUE TITLE
Click back for bubble notifications (request)

### ISSUE THREAD

**Issue by clarkewd** [mstratman/cocoadialog#36]
It would be fantastic to be able to define a "clickback" action for bubble notifications, or clickback inactions.

This would make it possible to launch a subsequent script based on a user's acknowledgement of the bubble notification, or even launch a script if they did not click the bubble.

**Comment by markcarver** [comment]
This isn't going to happen. It's just way too old and complex to be trying to add new features to this control.

I'll be replacing both the custom cocoaDialog "bubble" control and Growl support in 4.x.x with native macOS notification center support which will undoubtedly have this capability.
