### ISSUE TITLE
Show bubble/growl notification without an icon?

### ISSUE THREAD

**Issue by Tyilo** [mstratman/cocoadialog#38]
Is it possible to make the bubble run mode display no icon at all?

If growl doesn't support it, you could also bundle a completely transparent icon with cD and use that in growl.

**Comment by markcarver** [comment]
This isn't going to happen. It's just way too old and complex to be trying to add new features to this.

 I'll be replacing both the custom cocoaDialog "bubble" control and Growl support in 4.x.x with native macOS notification center support.
