### ISSUE TITLE
Allow text labels to be formatted using Markdown

### ISSUE THREAD

**Issue by sabinomaggi** [mstratman/cocoadialog#42]
Would it be possible to add the option to format the text in message boxes?

In particular, it would be useful to be able to change the dimension of the font (it is very small, imho), to emphasize some parts of the text (underlining or bold  should suffice), to insert hyperlinks, and to have separators between sections of text.

**Comment by markcarver** [comment]
I agree, Markdown would probably the most appropriate choice here.

I think it'd be ok to enable this by default. However, in the off chance that something isn't rendered right... we may want to provide a `--no-markdown` option.

https://github.com/indragiek/CocoaMarkdown
