### ISSUE TITLE
Minimize option with msgbox

### ISSUE THREAD

**Issue by vejmarie** [mstratman/cocoadialog#43]
Hi,

With latest version of cocoaDialog, there is no way to have a minimize option of the msgbox. Do you believe this is something which could happen in the near futur ? I need it for a small OpenVPN application, where the msgbox is used to inform the user he is connected, and to click a Disconnect button. Some of them are complaining about the fact that the window stay on top.

Jean-Marie

**Comment by markcarver** [comment]
https://github.com/mstratman/cocoadialog/commit/7131b321c41b7104a1a32cad3fb859c567156a46 added the `--close`, `--minimize` and `--resize` global options.
