### ISSUE TITLE
inputbox doesn't capture stdin

### ISSUE THREAD

**Issue by cabletie** [mstratman/cocoadialog#52]
I can't get input box (or variants) to capture stdin. The entered text just goes to the shell that CocoaDialog was called from. All the other runmodes work well.

I'm using the following wrapper:

``` perl
#!/usr/bin/perl
use strict;
use warnings;

my $path = "/Applications"; 
my $cd = "$path/cocoaDialog.app/Contents/MacOS/cocoaDialog";

system($cd, @ARGV);
```

but have also tried running binary directly.

I have tried v2.1.1 as well as 3.0.0-beta7. I have also tried cloning and building myself in case it was OS-X 10.8.2 related but no luck.

Am I doing something wrong?

Thanks for any pointers.
Peter

**Comment by markcarver** [comment]
The only control that uses `stdin` is the `progressbar` control (to handle progress updates).

The `inputbox` control does not. It uses the `--text` option in cocoaDialog 2 or the `--value` option in cocoaDialog 3.

The `textbox` control uses `--text` or `--text-from-file`.

In cocoaDialog, you can see what options any control has by doing:
`cocoaDialog <control> --help`.
