### ISSUE TITLE
-fsingle-precision-constant build error

### ISSUE THREAD

**Issue by bingalls** [mstratman/cocoadialog#55]
I am building on Lion 10.6. Thanks for your help. I tried removing "-fsingle-precision-constant" from the "Extra C Flags", but it still comes back

ProcessPCH /Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Intermediates/PrecompiledHeaders/cocoaDialog_Prefix-foaxnsihzfohksfbweyznpfflhny/cocoaDialog_Prefix.pch.pth Source/cocoaDialog_Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/bingalls/Source/cocoadialog
    setenv LANG en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c-header -arch x86_64 -fmessage-length=0 -std=c99 -Wno-trigraphs -O0 -Wmissing-field-initializers -Wno-missing-prototypes -Wreturn-type -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wduplicate-method-match -Wformat -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wuninitialized -Wunknown-pragmas -Wshadow -Wfour-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wenum-conversion -Wsign-compare -Wshorten-64-to-32 -Wno-pointer-sign -Wnewline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.6.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.5 -g -fvisibility=hidden -Wno-sign-conversion -I/Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Intermediates/cocoaDialog.build/Debug/relaunch.build/relaunch.hmap -I/Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Products/Debug/include "-I/Users/bingalls/Source/cocoadialog/Source/*" -I/Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Intermediates/cocoaDialog.build/Debug/relaunch.build/DerivedSources/x86_64 -I/Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Intermediates/cocoaDialog.build/Debug/relaunch.build/DerivedSources -Wall -Wno-unused-parameter -Werror -Wundef -Wendif-labels -Wpointer-arith -Wcast-align -Wwrite-strings -Wmissing-format-attribute -Wpacked -Wredundant-decls -Winline -Wdisabled-optimization -Wformat=2 -Winvalid-pch -F/Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Products/Debug -F/Users/bingalls/Source/cocoadialog/Frameworks -fsingle-precision-constant -DDEBUG --serialize-diagnostics /Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Intermediates/PrecompiledHeaders/cocoaDialog_Prefix-foaxnsihzfohksfbweyznpfflhny/cocoaDialog_Prefix.pch.dia -c /Users/bingalls/Source/cocoadialog/Source/cocoaDialog_Prefix.pch -o /Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Intermediates/PrecompiledHeaders/cocoaDialog_Prefix-foaxnsihzfohksfbweyznpfflhny/cocoaDialog_Prefix.pch.pth -MMD -MT dependencies -MF /Users/bingalls/Library/Developer/Xcode/DerivedData/cocoaDialog-fwjvqsvxqbjklscirgxyebukxmpw/Build/Intermediates/PrecompiledHeaders/cocoaDialog_Prefix-foaxnsihzfohksfbweyznpfflhny/cocoaDialog_Prefix.pch.d

clang: error: argument unused during compilation: '-fsingle-precision-constant'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

**Comment by markcarver** [comment]
This was taken care of in recent commits.
