### ISSUE TITLE
spaces in --click-path

### ISSUE THREAD

**Issue by systemheld** [mstratman/cocoadialog#63]
Hi!

I tried to open an Application while clicking on the cocoaDialog (3.0.0-beta7) notification. If the path specified in --click-path doesn't contain spaces, it will work. Tested this with:
CocoaDialog bubble --debug --title 'Updates' --text 'some Text' --click-path '/Applications/Calculator.app/Contents/MacOS/Calculator'

If the path contains spaces (e.g. when opening the Casper Suite Self Service), nothing happens:
CocoaDialog bubble --debug --title 'Updates' --text 'some Text' --click-path '/Applications/Self Service.app/Contents/MacOS/Self Service'

even if i escape the spaces ("/Applications/Self\ Service.app/Contents/MacOS/Self\ Service") noting happens. I've also tried to open the Application with: "open -a Self Service". 

I dont't use growl, if that matters.

Thanks for any advise,
Oliver

**Comment by markcarver** [comment]
I cannot reproduce.
