### ISSUE TITLE
Language Wrappers

### ISSUE THREAD

**Issue by ritashugisha** [mstratman/cocoadialog#67]
During development of a project called [The Alfred Bundler](https://github.com/shawnrice/alfred-bundler) I've created wrappers that allow our users to easily implement CocoaDialog.

I find these extremely useful for implementing CocoaDialog in other languages. Currently we support the following.

+ [PHP](https://github.com/shawnrice/alfred-bundler/blob/devel/bundler/includes/wrappers/php/cocoadialog.php)
+ [Python](https://github.com/shawnrice/alfred-bundler/blob/devel/bundler/includes/wrappers/python/wrappers/cocoadialog.py)
+ [Ruby](https://github.com/shawnrice/alfred-bundler/blob/devel/bundler/includes/wrappers/ruby/cocoadialog.rb)

We will *most likely* update the wrappers to the above links. But structure of the Alfred Bundler is due to change. 

I will update the link to the wrappers once I create a new repository for updating the wrappers.

**Comment by mralexgray** [comment]
@ritashugisha , @markcarver , @mstratman  what do you guys think of including these as part of the "examples".  I think this kind of functionality is core to the product.  @ritashugisha .. if these guys agree.. you could simply fork the project.. add a directory like "wrappers" to the examples folder, include your scripts, and commit to upstream..  that way, future development can coincide in parallel.  another way would be as a submodule.  what do you all think?  (ps: i haven't tested or used these wrappers).

**Comment by markcarver** [comment]
I think these wrappers are awesome and much needed! Especially the PHP one. I'd be curious to see if this were to every makes its way into [packagist](https://packagist.org/) and maybe utilize something like Symfony's [console component](http://symfony.com/doc/current/components/console/introduction.html).

> adding these wrappers to this specific repo/project

I really don't think this should happen.

The wrappers themselves do not actually provide any functionality other than to validate and convert how one is to invoke the cocoaDialog binary.

Also, this is an Obj-C project. We really shouldn't worry ourselves with the idiosyncrasies and issues for each wrapper (language). It would require this project (and us maintainers) to know each of these languages to officially support them (e.g. I know PHP very well and some Ruby, but I definitely don't know any Python and have no real desire to learn it).

I'd be happy to reference/mention these wrappers, once they're official and separate projects, in the project's documentation.
