### ISSUE TITLE
Changing textbox color and font color and size

### ISSUE THREAD

**Issue by siamak01** [mstratman/cocoadialog#72]
Is it possible to assign color and size to text and background of textbox?

**Comment by mstratman** [comment]
It's not but if you're feeling adventurous and it's a consistent size and color you need, it would be fairly easy to add to the nib.

**Comment by siamak01** [comment]
willing to try. 
How do you modify nib?

**Comment by mstratman** [comment]
Make sure you have xcode installed, go into the package contents, then the "Resources" folder, and double click one of the .xib files.

**Comment by siamak01** [comment]
I do not have xib in my Resources folder only nib files. I tried to open them up with nib. with Xcode. But only shows icon nothing else.
I have Xcode 6.1

**Comment by mstratman** [comment]
Try opening the Textbox.nib, then double click in the textbox, then pick the attributes inspector. From here you should be able to control many aspects of the textbox

**Comment by mstratman** [comment]
![2015-01-02 at 4 46 pm](https://cloud.githubusercontent.com/assets/317598/5600415/0821a3b6-929f-11e4-9d37-eb2e0d9b7a9e.png)

**Comment by siamak01** [comment]
this is all I get!

**Comment by siamak01** [comment]
I managed to open nib in version 2 but not 3!

**Comment by siamak01** [comment]
I changed what I needed except for textbox font size. it seems will not save the size and font. Maybe overridden by something. background as well as “Small System Font Text" font and size was satisfactoryly change thank you. I do not understand why nibs in version 3 could not open.
