### ISSUE TITLE
Web view control

### ISSUE THREAD

**Issue by mstratman** [mstratman/cocoadialog#75]
From Tim via the list https://lists.sourceforge.net/lists/listinfo/cocoadialog-users

> If anyone is still developing cocoaDialog I'd like to suggest a new run mode - webview. To be used as follows:
> 
>  cocoaDialog webview --url "http://www.example.com"
> 
>  would open a window and use the webkit interface to display the page at the given url. The window would have some default dimensions unless --height and --width are also specified. Window to remain open until it is closed in the usual way or the page issues a window.close() in JavaScript.
> 
> My impression is that this wouldn't require much code but unfortunately I have no knowledge of objective-C. The originator of this thread:
> 
>  http://forums.macrumors.com/threads/help-setting-up-webview.1077607/
> 
> appears to have succeeded, for instance.

**Comment by markcarver** [comment]
Closing as dup of #46
