### ISSUE TITLE
 when click one bubble,all the bubbles are not closing

### ISSUE THREAD

**Issue by rajeshecegce** [mstratman/cocoadialog#77]
I am using beta version for bubble resize base on content is not available in stable version.when click one bubble,all the bubbles are not closing(this default behaviour working in stable version).If it is fixed,it will helpful to me Thanks

**Comment by mralexgray** [comment]
@rajeshecegce can u upload a picture of what you're talking about? or some of the code of yours that isn't working correctly?  then i can try it myself to see if it's not something simple to fix..
