### ISSUE TITLE
Don't use button index for exitCode

### ISSUE THREAD

**Issue by Jyqft** [mstratman/cocoadialog#80]
I have this AppleScript, wherein I call on cocoaDialog to spawn a multi-line textbox:

```
do shell script "/Applications/CocoaDialog.app/Contents/MacOS/CocoaDialog \\
textbox --editable --focus-textbox --title 'Open URLs' --button1 Open --button2 Cancel"

set {button, answer} to paragraphs of result
if button is "1" then
    return answer
end if
```

When I press button 1 (Open), the error that gets thrown in Script Editor is:

```
error "1
<answer>" number 1
```

where `<answer>` is whatever was typed in the textbox.

When I press button 2 (Cancel), the error that gets thrown is:

```
error "2" number 2
```

I've tested this in bash and it worked perfectly there.

Why is it not working as intended in AppleScript?

I'm on Mac OS X 10.10.5 (14F1509).

---

x-ref: #28

**Comment by markcarver** [comment]
Because cocoaDialog is setting the exit code status to the button index, which is horrible and should be changed.

**Comment by markcarver** [comment]
Actually, this will need to be done in cocoaDialog 4 so we don't break backwards compatibility if anyone is actually relying on these exit codes.

**Comment by markcarver** [comment]
Considering that the 3.x version never left beta, this is technically not a "major breaking change". It should be resolved now before it gets to stable.
