### ISSUE TITLE
Remove Sparkle updater

### ISSUE THREAD

**Issue by franzinc** [mstratman/cocoadialog#81]
For reference, this is what I'm talking about:

https://vulnsec.com/2016/osx-apps-vulnerabilities/

**Comment by markcarver** [comment]
Probably.

That being said, there hasn't actually been any "updates" [in 5 years](https://github.com/mstratman/cocoadialog/releases). Furthermore, it requires one to manually execute the `update` sub-command in cocoaDialog.

I doubt the risk to anyone is that great.

Regardless, this project really doesn't need an updater. I'd rather it just be removed at this point.
