### ISSUE TITLE
Stoppable progressbar bash example that stops the loop

### ISSUE THREAD

**Issue by mikemcduffie** [mstratman/cocoadialog#84]
Hi,

I apologize if I'm being dense, but I can't see how to use Cocoadialog with a stoppable progressbar that does more than just dismiss the dialog. Is there some bash code or even a perl one-liner to observe stdout and exit the loop accordingly?

I tried the example code at [https://github.com/mstratman/cocoadialog/blob/master/Examples/progressbar.sh](url)

It appears the example is meant to use the notifier tool as the first argument but I'm confused on how to use it. Replacing `$1` with `terminal-notifier` does produce a progessbar dialog with a stop button and dismisses the dialog as expected. But if you change the code to:

`for x in $(seq 50); { X=$((x*2)); echo "$X Percent done:$X" > $PIPE; echo $x; sleep .1; }`

to make slow enough to observe and watch stdout, the loop never stops executing . I can see `stopped` in stdout when the dialog is dismissed, but the rest of the loop continues to 50 regardless.

Also, is it necessary to open the progressbar as a background task to even get a stop button?

I'm trying to loop through an array of filenames and want to add the option to abort:

`for FILE in "${FILES[@]}"`
`do`
`   ...`
`done > >($DIALOG_TOOL progressbar ‑‑stoppable --title "Testing Files")`

The code and progressbar work fine, I just can't abort if desired.

I also assume there's no way to make the progressbar dialog not float on top all the time. If there is I haven't found a way.

**Comment by Dragao75** [comment]
I have the same question.
I to want to abort the loop (in a bash script)

Can't figure out how.

(is there still development in CocoaDialog?)

**Comment by Dragao75** [comment]
I just found a solution for my problem. 
@mikemcduffie  this may help you as well.

Here is my code: 
`#!/bin/bash

timerSeconds="60"

cdPath="/Library/Application Support/JAMF/bin/CocoaDialog.app/Contents/MacOS/CocoaDialog"

rm -f /tmp/hpipe
mkfifo /tmp/hpipe
sleep 0.2

"$cdPath" progressbar --title "Scheduled Shutdown" --text "Preparing to shutdown this Mac..." \
--posX "center" --posY "199" --width 450 --float \
--stoppable \
--stop disble \
--icon-file "/System/Library/CoreServices/loginwindow.app/Contents/Resources/Shutdown.tiff" \
--icon-height 48 --icon-width 48 --height 90 < /tmp/hpipe **> /tmp_out** &

## Send progress through the named pipe
exec 3<> /tmp/hpipe

echo "100" >&3

sleep 1.5

startTime=`date +%s`
stopTime=$((startTime+timerSeconds))
secsLeft=$timerSeconds
progLeft="100"

while [[ "$secsLeft" -gt 0 ]]; do
    sleep 1
    **dialogStopCheck=`cat /tmp/_out`
	if [[ "$dialogStopCheck" = "stopped" ]]; then
		exit 1
	fi**
    currTime=`date +%s`
    progLeft=$((secsLeft*100/timerSeconds))
    secsLeft=$((stopTime-currTime))
    minRem=$((secsLeft/60))
    secRem=$((secsLeft%60))
    echo "$progLeft $minRem minute(s) $secRem seconds until your Mac will shutdown. Please save any work now." >&3
done
echo "SHUTDOWN"`

The Bold parts has the trick
