### ISSUE TITLE
Dialog Box is "smashed"

### ISSUE THREAD

**Issue by BambiB** [mstratman/cocoadialog#86]
When I run the example script for the pulldown, I get: 

![screen shot 2016-10-18 at 6 48 14 pm](https://cloud.githubusercontent.com/assets/8808403/19499280/927a1746-9563-11e6-8457-a7a607a91cec.png)

The selector is much wider than it should be and overlaps the buttons at the bottom.
The --height and --width don't seem to have any effect.

This is under Sierra with perl 5.24.

**Comment by mstratman** [comment]
Use version 2 and you should be fine.  Version 3 is beta and nobody is actively working to get it cleaned up and stable.

**Comment by BambiB** [comment]
Wow.  That was fast!  I'll check it out.

Thanks!!!

**Comment by markcarver** [comment]
Dup of #51
