### ISSUE TITLE
Progress bar does not display progress in macOS Sierra.

### ISSUE THREAD

**Issue by smashism** [mstratman/cocoadialog#88]
Some context ([start here and keeping reading down](https://www.jamf.com/jamf-nation/discussions/5404/jamfhelper-software-update-trigger#responseChild129759))… in macOS Sierra the progress bar will display but does not actually show progress.

![progressbarcd](https://cloud.githubusercontent.com/assets/7853266/21904008/a9ed864a-d8c7-11e6-8543-195357bec1fb.png)

I don't have a lot more details to include than that, as I'm not savvy enough to understand what changed.

**Comment by markcarver** [comment]
It still works in macOS Sierra (been using it just fine in some of my own apps).

My guess is that whatever is creating this is no longer sending progress via `STDIN`.

Per the [progress documentation](http://mstratman.github.io/cocoadialog/#documentation3.0/progressbar_control), you have to actually set the progress yourself.

There are many different ways to do this, in varying languages.
